### ISSUE TITLE
docs.rs generation for 1.1.0 is broken

### ISSUE THREAD

**Issue by philpax** [EqualGames/game-scanner#21]
## Expected Behavior

There should be documentation available for [game-scanner 1.1.0 here](https://docs.rs/crate/game-scanner/1.1.0).

## Current Behavior

Documentation generation appears to have failed due to `libsqlite3-sys` attempting to build outside of `OUT_DIR` [here](https://docs.rs/crate/game-scanner/1.1.0/builds/459660).

## Possible Solution

Not sure, but I assume this isn't a problem for other crates using `rusqlite`. Maybe try updating `rusqlite` and see if that fixes it?

## Steps to Reproduce (for bugs)

Publish a version to crates.io and wait for docs.rs to generate the docs pages.

## Context

I use docs.rs daily to look up how to operate libraries, but I wasn't able to do that with game-scanner due to the docs. Instead, I had to look at the code, which is always informative but not as efficient as having the docs available.

**Comment by philpax** [comment]
Ah, I see you've already gotten around to updating the deps in #20! Hopefully that fixes it 🙂 

Looking forward to the new release!

**Comment by matheusalbino** [comment]
New version published, let's see if now the docs.rs works.

**Comment by matheusalbino** [comment]
The new version has the same error (https://docs.rs/crate/game-scanner/1.1.1/builds/520996)

In the docs.rs configuration, I'm defining the default target to `x86_64-pc-windows-msvc` because the windows platform has all implementations.

In the version `1.0.1` doesn't have any configuration for docs.rs, and the default target is `x86_64-unknown-linux-gnu`.

So the conclusion is the build of `libsqlite3-sys` is failing only for windows target. Maybe needs some specific configuration for works correctly.

I will remove the target configuration and see if will display the documentation correctly.

**Comment by matheusalbino** [comment]
How today has more implementations than the version `1.0.1` and the linux target doesn't have all implementations, the docs.rs build broke.

Build Log: https://docs.rs/crate/game-scanner/1.1.2/builds/521008

This issue needs more research.

**Comment by matheusalbino** [comment]
@philpax now the doc.rs is working as expected.

https://docs.rs/game-scanner/1.1.3/game_scanner/index.html
